name: myfirstworkflow 

on: 
  workflow_dispatch  

jobs: 
  test_job: 

    runs-on: ubuntu-latest  
    steps: 
      - name: checkout 
        run: ls -lrt  

      - name: echo command 
        run: | 
          echo "This is my first job"